# The actual makefile is in another file!
# So, we'll just include that makefile.

# In this makefile we want make not to announce every command that it's running.
# -s causes make to not print out the commands it is running. 
MAKEFLAGS += -s

# -r removes "implicit rules" which are rules and recipes that make makes automatically without you writing them in the makefile at all. 
MAKEFLAGS += -r

include Makefile.advanced
